const PRODUCTION_PROCESS_NAME_REQUIRED = 'Name is required!';
const PRODUCTION_PROCESS_START_DATE_REQUIRED = 'Start date is required!';
const PRODUCTION_PROCESS_ITEMS_REQUIRED = 'Items are required!';

module.exports = {
  PRODUCTION_PROCESS_NAME_REQUIRED,
  PRODUCTION_PROCESS_START_DATE_REQUIRED,
  PRODUCTION_PROCESS_ITEMS_REQUIRED,
};
